### ISSUE TITLE
Folder issues.

### ISSUE THREAD

**Issue by Laizerox** [kooohei/brackets-synapse#36]
Hello, I'm experiencing something weird maybe due to security reasons.

I've linked /var/www to my home into html and I cannot access it using Brackets Synapse after connecting.

Also same issue happens if I try to set current dir to /var/www.

**Comment by kooohei** [comment]
"226 transfer done (but failed to open directory)", "chroot", "vsftpd", "selinux"
Is it likely that can be resolved by these keywords?

**Comment by kooohei** [comment]
fixed symlink problem ver 1.2.1
please try it.

**Comment by Laizerox** [comment]
1.2.2 doesn't load at all since it fails at Panel.js:185 with error: Uncaught TypeError: undefined is not a function

**Comment by Laizerox** [comment]
1.2.3 works now, but I still have issues loading symlink from /var/ww or /var/www without symlink.

It keeps "loading"

**Comment by kooohei** [comment]
what did setting use protocol ftp? or sftp?

**Comment by Laizerox** [comment]
sftp was used as protocol

**Comment by kooohei** [comment]
ok thx, I'll confirm that after arriving at the home.

**Comment by Laizerox** [comment]
I tested your latest build and the issue seems to be fixed!

**Comment by kooohei** [comment]
thanx for the report.
but I work up waiting a log of you.
and 1.2.83 now available, this is fixed scroll problem.
please try it.
